function createimage(cdata1, Parent1)
%CREATEIMAGE(cdata1, Parent1)
%  CDATA1:  image cdata
%  PARENT1:  image parent

%  Auto-generated by MATLAB on 28-Jun-2021 16:07:53

% Create image
image([1000 4000],[0 1],cdata1,'Parent',Parent1);

